# SPDX-License-Identifier: Apache-2.0
version: "2"
run:
  timeout: 5m
  exclude-dirs:
    - vendor
    - build
    - release
  build-tags:
    - pkcs11

formatters:
  enable:
#    - gci
#    - gofumpt
    - gofmt
    - goimports

linters:
  default: none
  enable:
    - asciicheck
#    - bodyclose
#    - copyloopvar
    - decorder
    - depguard
#    - dupword
#    - durationcheck
#    - errorlint
    - gocheckcompilerdirectives
    - goheader
    - gomodguard_v2
    - goprintffuncname
    - govet
    - grouper
#    - ineffassign
#    - intrange
    - loggercheck
#    - misspell
#    - modernize
    - nolintlint
    - nosprintfhostport
#    - perfsprint
    - promlinter
#    - protogetter
    - reassign
    - sloglint
    - spancheck
#    - staticcheck
    - testableexamples
#    - testifylint
#    - tparallel
#    - unconvert
#    - usestdlibvars
#    - usetesting
#    - whitespace
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: "golang.org/x/net/context"
              desc: "use 'context' from stdlib instead"
            - pkg: "github.com/gogo/protobuf"
              desc: "use 'github.com/golang/protobuf' instead"
    govet:
      settings:
        printf:
          funcs:
            - Debug
            - Debugf
            - Print
            - Printf
            - Info
            - Infof
            - Warning
            - Warningf
            - Error
            - Errorf
            - Critical
            - Criticalf
            - Sprint
            - Sprintf
            - Log
            - Logf
            - Panic
            - Panicf
            - Fatal
            - Fatalf
            - Notice
            - Noticef
            - Wrap
            - Wrapf
            - WithMessage
    staticcheck:
      checks: ["all", "-SA1019", "-ST1000", "-ST1003", "-ST1005", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
      dot-import-whitelist:
        - github.com/onsi/gomega
        - github.com/onsi/ginkgo/v2

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
