// Code generated by protoc-gen-go.
// source: common/msp_principal.proto
// DO NOT EDIT!

package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MSPPrincipal_Classification int32

const (
	// XXX Change all to UPPER_CASE
	MSPPrincipal_ByMSPRole MSPPrincipal_Classification = 0
	// one of a member of MSP network, and the one of an
	// administrator of an MSP network
	MSPPrincipal_ByOrganizationUnit MSPPrincipal_Classification = 1
	// groupping of entities, per MSP affiliation
	// E.g., this can well be represented by an MSP's
	// Organization unit
	MSPPrincipal_ByIdentity MSPPrincipal_Classification = 2
)

var MSPPrincipal_Classification_name = map[int32]string{
	0: "ByMSPRole",
	1: "ByOrganizationUnit",
	2: "ByIdentity",
}
var MSPPrincipal_Classification_value = map[string]int32{
	"ByMSPRole":          0,
	"ByOrganizationUnit": 1,
	"ByIdentity":         2,
}

func (x MSPPrincipal_Classification) String() string {
	return proto.EnumName(MSPPrincipal_Classification_name, int32(x))
}
func (MSPPrincipal_Classification) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor4, []int{0, 0}
}

type MSPRole_MSPRoleType int32

const (
	MSPRole_Member MSPRole_MSPRoleType = 0
	MSPRole_Admin  MSPRole_MSPRoleType = 1
)

var MSPRole_MSPRoleType_name = map[int32]string{
	0: "Member",
	1: "Admin",
}
var MSPRole_MSPRoleType_value = map[string]int32{
	"Member": 0,
	"Admin":  1,
}

func (x MSPRole_MSPRoleType) String() string {
	return proto.EnumName(MSPRole_MSPRoleType_name, int32(x))
}
func (MSPRole_MSPRoleType) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{2, 0} }

// MSPPrincipal aims to represent an MSP-centric set of identities.
// In particular, this structure allows for definition of
//  - a group of identities that are member of the same MSP
//  - a group of identities that are member of the same organization unit
//    in the same MSP
//  - a group of identities that are administering a specific MSP
//  - a specific identity
// Expressing these groups is done given two fields of the fields below
//  - Classification, that defines the type of classification of identities
//    in an MSP this principal would be defined on; Classification can take
//    three values:
//     (i)  ByMSPRole: that represents a classification of identities within
//          MSP based on one of the two pre-defined MSP rules, "member" and "admin"
//     (ii) ByOrganizationUnit: that represents a classification of identities
//          within MSP based on the organization unit an identity belongs to
//     (iii)ByIdentity that denotes that MSPPrincipal is mapped to a single
//          identity/certificate; this would mean that the Principal bytes
//          message
type MSPPrincipal struct {
	// Classification describes the way that one should process
	// Principal. An Classification value of "ByOrganizationUnit" reflects
	// that "Principal" contains the name of an organization this MSP
	// handles. A Classification value "ByIdentity" means that
	// "Principal" contains a specific identity. Default value
	// denotes that Principal contains one of the groups by
	// default supported by all MSPs ("admin" or "member").
	PrincipalClassification MSPPrincipal_Classification `protobuf:"varint,1,opt,name=principal_classification,json=principalClassification,enum=common.MSPPrincipal_Classification" json:"principal_classification,omitempty"`
	// Principal completes the policy principal definition. For the default
	// principal types, Principal can be either "Admin" or "Member".
	// For the ByOrganizationUnit/ByIdentity values of Classification,
	// PolicyPrincipal acquires its value from an organization unit or
	// identity, respectively.
	Principal []byte `protobuf:"bytes,2,opt,name=principal,proto3" json:"principal,omitempty"`
}

func (m *MSPPrincipal) Reset()                    { *m = MSPPrincipal{} }
func (m *MSPPrincipal) String() string            { return proto.CompactTextString(m) }
func (*MSPPrincipal) ProtoMessage()               {}
func (*MSPPrincipal) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

// OrganizationUnit governs the organization of the Principal
// field of a policy principal when a specific organization unity members
// are to be defined within a policy principal.
type OrganizationUnit struct {
	// MSPIdentifier represents the identifier of the MSP this organization unit
	// refers to
	MSPIdentifier string `protobuf:"bytes,1,opt,name=MSPIdentifier" json:"MSPIdentifier,omitempty"`
	// OrganizationUnitIdentifier defines the organization unit under the
	// MSP identified with MSPIdentifier
	OrganizationalUnitIdentifier string `protobuf:"bytes,2,opt,name=organizational_unit_identifier,json=organizationalUnitIdentifier" json:"organizational_unit_identifier,omitempty"`
}

func (m *OrganizationUnit) Reset()                    { *m = OrganizationUnit{} }
func (m *OrganizationUnit) String() string            { return proto.CompactTextString(m) }
func (*OrganizationUnit) ProtoMessage()               {}
func (*OrganizationUnit) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

// MSPRole governs the organization of the Principal
// field of an MSPPrincipal when it aims to define one of the
// two dedicated roles within an MSP: Admin and Members.
type MSPRole struct {
	// MSPIdentifier represents the identifier of the MSP this principal
	// refers to
	MSPIdentifier string `protobuf:"bytes,1,opt,name=MSPIdentifier" json:"MSPIdentifier,omitempty"`
	// MSPRoleType defines which of the available, pre-defined MSP-roles
	// an identiy should posess inside the MSP with identifier MSPidentifier
	Role MSPRole_MSPRoleType `protobuf:"varint,2,opt,name=Role,enum=common.MSPRole_MSPRoleType" json:"Role,omitempty"`
}

func (m *MSPRole) Reset()                    { *m = MSPRole{} }
func (m *MSPRole) String() string            { return proto.CompactTextString(m) }
func (*MSPRole) ProtoMessage()               {}
func (*MSPRole) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func init() {
	proto.RegisterType((*MSPPrincipal)(nil), "common.MSPPrincipal")
	proto.RegisterType((*OrganizationUnit)(nil), "common.OrganizationUnit")
	proto.RegisterType((*MSPRole)(nil), "common.MSPRole")
	proto.RegisterEnum("common.MSPPrincipal_Classification", MSPPrincipal_Classification_name, MSPPrincipal_Classification_value)
	proto.RegisterEnum("common.MSPRole_MSPRoleType", MSPRole_MSPRoleType_name, MSPRole_MSPRoleType_value)
}

func init() { proto.RegisterFile("common/msp_principal.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x4b, 0xc3, 0x30,
	0x1c, 0xc5, 0xd7, 0xa1, 0x93, 0xfe, 0xdd, 0x4a, 0xc9, 0x41, 0x87, 0x0e, 0x19, 0x75, 0x87, 0x81,
	0xd8, 0xc2, 0xfc, 0x04, 0x56, 0x41, 0x3c, 0x14, 0x4b, 0xa7, 0x17, 0x0f, 0x96, 0xb6, 0xcb, 0xb6,
	0x3f, 0xb4, 0x49, 0x49, 0xb3, 0x43, 0x3d, 0x78, 0xf4, 0x1b, 0xfa, 0x7d, 0xa4, 0xa9, 0xdb, 0xda,
	0x9d, 0x3c, 0x85, 0xbc, 0xf7, 0x7b, 0xef, 0x9f, 0x84, 0xc0, 0x45, 0xc2, 0xb3, 0x8c, 0x33, 0x27,
	0x2b, 0xf2, 0x30, 0x17, 0xc8, 0x12, 0xcc, 0xa3, 0xd4, 0xce, 0x05, 0x97, 0x9c, 0xf4, 0x6a, 0xcf,
	0xfa, 0xd1, 0xa0, 0xef, 0xcd, 0x7d, 0x7f, 0x6b, 0x93, 0x0f, 0x18, 0xee, 0xd8, 0x30, 0x49, 0xa3,
	0xa2, 0xc0, 0x25, 0x26, 0x91, 0x44, 0xce, 0x86, 0xda, 0x58, 0x9b, 0x1a, 0xb3, 0x6b, 0xbb, 0xce,
	0xda, 0xcd, 0x9c, 0xfd, 0xd0, 0x42, 0x83, 0xf3, 0x5d, 0x49, 0xdb, 0x20, 0x23, 0xd0, 0x77, 0xd6,
	0xb0, 0x3b, 0xd6, 0xa6, 0xfd, 0x60, 0x2f, 0x58, 0x4f, 0x60, 0x1c, 0xf0, 0x03, 0xd0, 0xdd, 0xd2,
	0x9b, 0xfb, 0x01, 0x4f, 0xa9, 0xd9, 0x21, 0x67, 0x40, 0xdc, 0xf2, 0x45, 0xac, 0x22, 0x86, 0x9f,
	0x0a, 0x78, 0x63, 0x28, 0x4d, 0x8d, 0x18, 0x00, 0x6e, 0xf9, 0xbc, 0xa0, 0x4c, 0xa2, 0x2c, 0xcd,
	0xae, 0xf5, 0x05, 0xe6, 0x21, 0x45, 0x26, 0x30, 0xf0, 0xe6, 0x7e, 0x0d, 0x2d, 0x91, 0x0a, 0x75,
	0x1f, 0x3d, 0x68, 0x8b, 0xe4, 0x11, 0xae, 0x78, 0x23, 0x19, 0xa5, 0xe1, 0x86, 0xa1, 0x0c, 0x71,
	0x1f, 0xeb, 0xaa, 0xd8, 0xa8, 0x4d, 0x55, 0x13, 0xf6, 0x2d, 0xd6, 0xb7, 0x06, 0x27, 0x7f, 0xa7,
	0xfe, 0xe7, 0x5c, 0x07, 0x8e, 0x2a, 0x5a, 0xb5, 0x1b, 0xb3, 0xcb, 0xc6, 0x23, 0x57, 0xf2, 0x76,
	0x7d, 0x2d, 0x73, 0x1a, 0x28, 0xd0, 0x9a, 0xc0, 0x69, 0x43, 0x24, 0x00, 0x3d, 0x8f, 0x66, 0x31,
	0x15, 0x66, 0x87, 0xe8, 0x70, 0x7c, 0xbf, 0xc8, 0x90, 0x99, 0x9a, 0x7b, 0xfb, 0x7e, 0xb3, 0x42,
	0xb9, 0xde, 0xc4, 0x55, 0xa1, 0xb3, 0x2e, 0x73, 0x2a, 0x52, 0xba, 0x58, 0x51, 0xe1, 0x2c, 0xa3,
	0x58, 0x60, 0xe2, 0xa8, 0xff, 0x50, 0x38, 0xf5, 0xb8, 0xb8, 0xa7, 0xb6, 0x77, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xd6, 0xf3, 0xc4, 0xb4, 0x3c, 0x02, 0x00, 0x00,
}
