// Code generated by protoc-gen-go.
// source: orderer/configuration.proto
// DO NOT EDIT!

package orderer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ConsensusType struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
}

func (m *ConsensusType) Reset()                    { *m = ConsensusType{} }
func (m *ConsensusType) String() string            { return proto.CompactTextString(m) }
func (*ConsensusType) ProtoMessage()               {}
func (*ConsensusType) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type BatchSize struct {
	// Simply specified as number of messages for now, in the future
	// we may want to allow this to be specified by size in bytes
	MaxMessageCount uint32 `protobuf:"varint,1,opt,name=maxMessageCount" json:"maxMessageCount,omitempty"`
	// The byte count of the serialized messages in a batch cannot
	// exceed this value.
	AbsoluteMaxBytes uint32 `protobuf:"varint,2,opt,name=absoluteMaxBytes" json:"absoluteMaxBytes,omitempty"`
	// The byte count of the serialized messages in a batch should not
	// exceed this value.
	PreferredMaxBytes uint32 `protobuf:"varint,3,opt,name=preferredMaxBytes" json:"preferredMaxBytes,omitempty"`
}

func (m *BatchSize) Reset()                    { *m = BatchSize{} }
func (m *BatchSize) String() string            { return proto.CompactTextString(m) }
func (*BatchSize) ProtoMessage()               {}
func (*BatchSize) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type BatchTimeout struct {
	// Any duration string parseable by ParseDuration():
	// https://golang.org/pkg/time/#ParseDuration
	Timeout string `protobuf:"bytes,1,opt,name=timeout" json:"timeout,omitempty"`
}

func (m *BatchTimeout) Reset()                    { *m = BatchTimeout{} }
func (m *BatchTimeout) String() string            { return proto.CompactTextString(m) }
func (*BatchTimeout) ProtoMessage()               {}
func (*BatchTimeout) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

// When submitting a new chain configuration transaction to create a new chain,
// the first configuration item must be of type Orderer with Key CreationPolicy
// and contents of a Marshaled CreationPolicy. The policy should be set to the
// policy which was supplied by the ordering service for the client's chain
// creation. The digest should be the hash of the concatenation of the remaining
// ConfigurationItem bytes. The signatures of the configuration item should
// satisfy the policy for chain creation.
type CreationPolicy struct {
	// The name of the policy which should be used to validate the creation of
	// this chain
	Policy string `protobuf:"bytes,1,opt,name=policy" json:"policy,omitempty"`
}

func (m *CreationPolicy) Reset()                    { *m = CreationPolicy{} }
func (m *CreationPolicy) String() string            { return proto.CompactTextString(m) }
func (*CreationPolicy) ProtoMessage()               {}
func (*CreationPolicy) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

// ChainCreationPolicyNames is the set of policies which may be invoked for chain creation
type ChainCreationPolicyNames struct {
	// A list of policies, in evaluation these are 'or'-ed, note this is not a proper policy
	// because implementing referential policies in a general way is difficult, and dangerous
	Names []string `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
}

func (m *ChainCreationPolicyNames) Reset()                    { *m = ChainCreationPolicyNames{} }
func (m *ChainCreationPolicyNames) String() string            { return proto.CompactTextString(m) }
func (*ChainCreationPolicyNames) ProtoMessage()               {}
func (*ChainCreationPolicyNames) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

// Carries a list of bootstrap brokers, i.e. this is not the exclusive set of
// brokers an ordering service
type KafkaBrokers struct {
	// Each broker here should be identified using the (IP|host):port notation,
	// e.g. 127.0.0.1:7050, or localhost:7050 are valid entries
	Brokers []string `protobuf:"bytes,1,rep,name=brokers" json:"brokers,omitempty"`
}

func (m *KafkaBrokers) Reset()                    { *m = KafkaBrokers{} }
func (m *KafkaBrokers) String() string            { return proto.CompactTextString(m) }
func (*KafkaBrokers) ProtoMessage()               {}
func (*KafkaBrokers) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

// ChannelRestrictions is the mssage which conveys restrictions on channel creation for an orderer
type ChannelRestrictions struct {
	MaxCount uint64 `protobuf:"varint,1,opt,name=max_count,json=maxCount" json:"max_count,omitempty"`
}

func (m *ChannelRestrictions) Reset()                    { *m = ChannelRestrictions{} }
func (m *ChannelRestrictions) String() string            { return proto.CompactTextString(m) }
func (*ChannelRestrictions) ProtoMessage()               {}
func (*ChannelRestrictions) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func init() {
	proto.RegisterType((*ConsensusType)(nil), "orderer.ConsensusType")
	proto.RegisterType((*BatchSize)(nil), "orderer.BatchSize")
	proto.RegisterType((*BatchTimeout)(nil), "orderer.BatchTimeout")
	proto.RegisterType((*CreationPolicy)(nil), "orderer.CreationPolicy")
	proto.RegisterType((*ChainCreationPolicyNames)(nil), "orderer.ChainCreationPolicyNames")
	proto.RegisterType((*KafkaBrokers)(nil), "orderer.KafkaBrokers")
	proto.RegisterType((*ChannelRestrictions)(nil), "orderer.ChannelRestrictions")
}

func init() { proto.RegisterFile("orderer/configuration.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x91, 0x5f, 0x8b, 0x9b, 0x40,
	0x14, 0xc5, 0xb1, 0x49, 0x93, 0x7a, 0x69, 0xfa, 0x67, 0x5a, 0x8a, 0x90, 0x97, 0x60, 0x29, 0x48,
	0x09, 0x5a, 0xda, 0x6f, 0xa0, 0x8f, 0x25, 0xa5, 0xd8, 0xf4, 0xa5, 0x2f, 0x65, 0x34, 0x57, 0x1d,
	0xa2, 0x33, 0x72, 0x67, 0x04, 0xdd, 0x2f, 0xb1, 0x5f, 0x79, 0x71, 0x34, 0x61, 0x77, 0xf3, 0x76,
	0xce, 0xbd, 0x3f, 0x98, 0x33, 0xf7, 0xc0, 0x56, 0xd1, 0x09, 0x09, 0x29, 0xca, 0x95, 0x2c, 0x44,
	0xd9, 0x11, 0x37, 0x42, 0xc9, 0xb0, 0x25, 0x65, 0x14, 0x5b, 0xcf, 0x4b, 0xff, 0x33, 0x6c, 0x12,
	0x25, 0x35, 0x4a, 0xdd, 0xe9, 0xe3, 0xd0, 0x22, 0x63, 0xb0, 0x34, 0x43, 0x8b, 0x9e, 0xb3, 0x73,
	0x02, 0x37, 0xb5, 0xda, 0xbf, 0x77, 0xc0, 0x8d, 0xb9, 0xc9, 0xab, 0x3f, 0xe2, 0x0e, 0x59, 0x00,
	0x6f, 0x1b, 0xde, 0x1f, 0x50, 0x6b, 0x5e, 0x62, 0xa2, 0x3a, 0x69, 0x2c, 0xbc, 0x49, 0x9f, 0x8f,
	0xd9, 0x57, 0x78, 0xc7, 0x33, 0xad, 0xea, 0xce, 0xe0, 0x81, 0xf7, 0xf1, 0x60, 0x50, 0x7b, 0x2f,
	0x2c, 0x7a, 0x33, 0x67, 0x7b, 0x78, 0xdf, 0x12, 0x16, 0x48, 0x84, 0xa7, 0x2b, 0xbc, 0xb0, 0xf0,
	0xed, 0xc2, 0x0f, 0xe0, 0xb5, 0x0d, 0x74, 0x14, 0x0d, 0xaa, 0xce, 0x30, 0x0f, 0xd6, 0x66, 0x92,
	0x73, 0xf0, 0x8b, 0xf5, 0x03, 0x78, 0x93, 0x10, 0xda, 0xbf, 0xff, 0x56, 0xb5, 0xc8, 0x07, 0xf6,
	0x09, 0x56, 0xad, 0x55, 0x33, 0x3a, 0x3b, 0xff, 0x1b, 0x78, 0x49, 0xc5, 0x85, 0x7c, 0x8a, 0xff,
	0xe2, 0x0d, 0x6a, 0xf6, 0x11, 0x5e, 0xca, 0x51, 0x78, 0xce, 0x6e, 0x11, 0xb8, 0xe9, 0x64, 0xc6,
	0x14, 0x3f, 0x79, 0x71, 0xe6, 0x31, 0xa9, 0x33, 0x92, 0x1e, 0x53, 0x64, 0x93, 0x9c, 0xb9, 0x8b,
	0xf5, 0xbf, 0xc3, 0x87, 0xa4, 0xe2, 0x52, 0x62, 0x9d, 0xa2, 0x36, 0x24, 0xf2, 0xf1, 0x01, 0xcd,
	0xb6, 0xe0, 0x36, 0xbc, 0xff, 0x9f, 0x5f, 0x8f, 0xb8, 0x4c, 0x5f, 0x35, 0xbc, 0xb7, 0xd7, 0x8b,
	0xff, 0xc2, 0x17, 0x45, 0x65, 0x58, 0x0d, 0x2d, 0x52, 0x8d, 0xa7, 0x12, 0x29, 0x2c, 0x78, 0x46,
	0x22, 0x9f, 0x3a, 0xd4, 0xe1, 0xdc, 0xe1, 0xbf, 0x7d, 0x29, 0x4c, 0xd5, 0x65, 0x61, 0xae, 0x9a,
	0xe8, 0x11, 0x1d, 0x4d, 0x74, 0x34, 0xd1, 0xd1, 0x4c, 0x67, 0x2b, 0xeb, 0x7f, 0x3c, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xeb, 0x0b, 0x25, 0xfc, 0x20, 0x02, 0x00, 0x00,
}
