//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: db_value.proto

package statekvdb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DBValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       []byte                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBValue) Reset() {
	*x = DBValue{}
	mi := &file_db_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBValue) ProtoMessage() {}

func (x *DBValue) ProtoReflect() protoreflect.Message {
	mi := &file_db_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBValue.ProtoReflect.Descriptor instead.
func (*DBValue) Descriptor() ([]byte, []int) {
	return file_db_value_proto_rawDescGZIP(), []int{0}
}

func (x *DBValue) GetVersion() []byte {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *DBValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *DBValue) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_db_value_proto protoreflect.FileDescriptor

const file_db_value_proto_rawDesc = "" +
	"\n" +
	"\x0edb_value.proto\x12\tstatekvdb\"U\n" +
	"\aDBValue\x12\x18\n" +
	"\aversion\x18\x01 \x01(\fR\aversion\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\fR\bmetadataBMZKgithub.com/hyperledger/fabric/core/ledger/kvledger/txmgmt/statedb/statekvdbb\x06proto3"

var (
	file_db_value_proto_rawDescOnce sync.Once
	file_db_value_proto_rawDescData []byte
)

func file_db_value_proto_rawDescGZIP() []byte {
	file_db_value_proto_rawDescOnce.Do(func() {
		file_db_value_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_db_value_proto_rawDesc), len(file_db_value_proto_rawDesc)))
	})
	return file_db_value_proto_rawDescData
}

var file_db_value_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_db_value_proto_goTypes = []any{
	(*DBValue)(nil), // 0: statekvdb.DBValue
}
var file_db_value_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_db_value_proto_init() }
func file_db_value_proto_init() {
	if File_db_value_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_db_value_proto_rawDesc), len(file_db_value_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_db_value_proto_goTypes,
		DependencyIndexes: file_db_value_proto_depIdxs,
		MessageInfos:      file_db_value_proto_msgTypes,
	}.Build()
	File_db_value_proto = out.File
	file_db_value_proto_goTypes = nil
	file_db_value_proto_depIdxs = nil
}
