// Code generated by protoc-gen-go.
// source: peer/chaincode.proto
// DO NOT EDIT!

package peer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Confidentiality Levels
type ConfidentialityLevel int32

const (
	ConfidentialityLevel_PUBLIC       ConfidentialityLevel = 0
	ConfidentialityLevel_CONFIDENTIAL ConfidentialityLevel = 1
)

var ConfidentialityLevel_name = map[int32]string{
	0: "PUBLIC",
	1: "CONFIDENTIAL",
}
var ConfidentialityLevel_value = map[string]int32{
	"PUBLIC":       0,
	"CONFIDENTIAL": 1,
}

func (x ConfidentialityLevel) String() string {
	return proto.EnumName(ConfidentialityLevel_name, int32(x))
}
func (ConfidentialityLevel) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type ChaincodeSpec_Type int32

const (
	ChaincodeSpec_UNDEFINED ChaincodeSpec_Type = 0
	ChaincodeSpec_GOLANG    ChaincodeSpec_Type = 1
	ChaincodeSpec_NODE      ChaincodeSpec_Type = 2
	ChaincodeSpec_CAR       ChaincodeSpec_Type = 3
	ChaincodeSpec_JAVA      ChaincodeSpec_Type = 4
)

var ChaincodeSpec_Type_name = map[int32]string{
	0: "UNDEFINED",
	1: "GOLANG",
	2: "NODE",
	3: "CAR",
	4: "JAVA",
}
var ChaincodeSpec_Type_value = map[string]int32{
	"UNDEFINED": 0,
	"GOLANG":    1,
	"NODE":      2,
	"CAR":       3,
	"JAVA":      4,
}

func (x ChaincodeSpec_Type) String() string {
	return proto.EnumName(ChaincodeSpec_Type_name, int32(x))
}
func (ChaincodeSpec_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 0} }

type ChaincodeDeploymentSpec_ExecutionEnvironment int32

const (
	ChaincodeDeploymentSpec_DOCKER ChaincodeDeploymentSpec_ExecutionEnvironment = 0
	ChaincodeDeploymentSpec_SYSTEM ChaincodeDeploymentSpec_ExecutionEnvironment = 1
)

var ChaincodeDeploymentSpec_ExecutionEnvironment_name = map[int32]string{
	0: "DOCKER",
	1: "SYSTEM",
}
var ChaincodeDeploymentSpec_ExecutionEnvironment_value = map[string]int32{
	"DOCKER": 0,
	"SYSTEM": 1,
}

func (x ChaincodeDeploymentSpec_ExecutionEnvironment) String() string {
	return proto.EnumName(ChaincodeDeploymentSpec_ExecutionEnvironment_name, int32(x))
}
func (ChaincodeDeploymentSpec_ExecutionEnvironment) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor1, []int{3, 0}
}

type ChaincodeMessage_Type int32

const (
	ChaincodeMessage_UNDEFINED               ChaincodeMessage_Type = 0
	ChaincodeMessage_REGISTER                ChaincodeMessage_Type = 1
	ChaincodeMessage_REGISTERED              ChaincodeMessage_Type = 2
	ChaincodeMessage_INIT                    ChaincodeMessage_Type = 3
	ChaincodeMessage_READY                   ChaincodeMessage_Type = 4
	ChaincodeMessage_TRANSACTION             ChaincodeMessage_Type = 5
	ChaincodeMessage_COMPLETED               ChaincodeMessage_Type = 6
	ChaincodeMessage_ERROR                   ChaincodeMessage_Type = 7
	ChaincodeMessage_GET_STATE               ChaincodeMessage_Type = 8
	ChaincodeMessage_PUT_STATE               ChaincodeMessage_Type = 9
	ChaincodeMessage_DEL_STATE               ChaincodeMessage_Type = 10
	ChaincodeMessage_INVOKE_CHAINCODE        ChaincodeMessage_Type = 11
	ChaincodeMessage_RESPONSE                ChaincodeMessage_Type = 13
	ChaincodeMessage_RANGE_QUERY_STATE       ChaincodeMessage_Type = 14
	ChaincodeMessage_RANGE_QUERY_STATE_NEXT  ChaincodeMessage_Type = 15
	ChaincodeMessage_RANGE_QUERY_STATE_CLOSE ChaincodeMessage_Type = 16
	ChaincodeMessage_KEEPALIVE               ChaincodeMessage_Type = 17
)

var ChaincodeMessage_Type_name = map[int32]string{
	0:  "UNDEFINED",
	1:  "REGISTER",
	2:  "REGISTERED",
	3:  "INIT",
	4:  "READY",
	5:  "TRANSACTION",
	6:  "COMPLETED",
	7:  "ERROR",
	8:  "GET_STATE",
	9:  "PUT_STATE",
	10: "DEL_STATE",
	11: "INVOKE_CHAINCODE",
	13: "RESPONSE",
	14: "RANGE_QUERY_STATE",
	15: "RANGE_QUERY_STATE_NEXT",
	16: "RANGE_QUERY_STATE_CLOSE",
	17: "KEEPALIVE",
}
var ChaincodeMessage_Type_value = map[string]int32{
	"UNDEFINED":               0,
	"REGISTER":                1,
	"REGISTERED":              2,
	"INIT":                    3,
	"READY":                   4,
	"TRANSACTION":             5,
	"COMPLETED":               6,
	"ERROR":                   7,
	"GET_STATE":               8,
	"PUT_STATE":               9,
	"DEL_STATE":               10,
	"INVOKE_CHAINCODE":        11,
	"RESPONSE":                13,
	"RANGE_QUERY_STATE":       14,
	"RANGE_QUERY_STATE_NEXT":  15,
	"RANGE_QUERY_STATE_CLOSE": 16,
	"KEEPALIVE":               17,
}

func (x ChaincodeMessage_Type) String() string {
	return proto.EnumName(ChaincodeMessage_Type_name, int32(x))
}
func (ChaincodeMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{6, 0} }

// ChaincodeID contains the path as specified by the deploy transaction
// that created it as well as the hashCode that is generated by the
// system for the path. From the user level (ie, CLI, REST API and so on)
// deploy transaction is expected to provide the path and other requests
// are expected to provide the hashCode. The other value will be ignored.
// Internally, the structure could contain both values. For instance, the
// hashCode will be set when first generated using the path
type ChaincodeID struct {
	// deploy transaction will use the path
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	// all other requests will use the name (really a hashcode) generated by
	// the deploy transaction
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *ChaincodeID) Reset()                    { *m = ChaincodeID{} }
func (m *ChaincodeID) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeID) ProtoMessage()               {}
func (*ChaincodeID) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// Carries the chaincode function and its arguments.
// UnmarshalJSON in transaction.go converts the string-based REST/JSON input to
// the []byte-based current ChaincodeInput structure.
type ChaincodeInput struct {
	Args [][]byte `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
}

func (m *ChaincodeInput) Reset()                    { *m = ChaincodeInput{} }
func (m *ChaincodeInput) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeInput) ProtoMessage()               {}
func (*ChaincodeInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

// Carries the chaincode specification. This is the actual metadata required for
// defining a chaincode.
type ChaincodeSpec struct {
	Type                 ChaincodeSpec_Type   `protobuf:"varint,1,opt,name=type,enum=protos.ChaincodeSpec_Type" json:"type,omitempty"`
	ChaincodeID          *ChaincodeID         `protobuf:"bytes,2,opt,name=chaincodeID" json:"chaincodeID,omitempty"`
	CtorMsg              *ChaincodeInput      `protobuf:"bytes,3,opt,name=ctorMsg" json:"ctorMsg,omitempty"`
	Timeout              int32                `protobuf:"varint,4,opt,name=timeout" json:"timeout,omitempty"`
	ConfidentialityLevel ConfidentialityLevel `protobuf:"varint,5,opt,name=confidentialityLevel,enum=protos.ConfidentialityLevel" json:"confidentialityLevel,omitempty"`
	Metadata             []byte               `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Attributes           []string             `protobuf:"bytes,7,rep,name=attributes" json:"attributes,omitempty"`
}

func (m *ChaincodeSpec) Reset()                    { *m = ChaincodeSpec{} }
func (m *ChaincodeSpec) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeSpec) ProtoMessage()               {}
func (*ChaincodeSpec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ChaincodeSpec) GetChaincodeID() *ChaincodeID {
	if m != nil {
		return m.ChaincodeID
	}
	return nil
}

func (m *ChaincodeSpec) GetCtorMsg() *ChaincodeInput {
	if m != nil {
		return m.CtorMsg
	}
	return nil
}

// Specify the deployment of a chaincode.
// TODO: Define `codePackage`.
type ChaincodeDeploymentSpec struct {
	ChaincodeSpec *ChaincodeSpec `protobuf:"bytes,1,opt,name=chaincodeSpec" json:"chaincodeSpec,omitempty"`
	// Controls when the chaincode becomes executable.
	EffectiveDate *google_protobuf1.Timestamp                  `protobuf:"bytes,2,opt,name=effectiveDate" json:"effectiveDate,omitempty"`
	CodePackage   []byte                                       `protobuf:"bytes,3,opt,name=codePackage,proto3" json:"codePackage,omitempty"`
	ExecEnv       ChaincodeDeploymentSpec_ExecutionEnvironment `protobuf:"varint,4,opt,name=execEnv,enum=protos.ChaincodeDeploymentSpec_ExecutionEnvironment" json:"execEnv,omitempty"`
}

func (m *ChaincodeDeploymentSpec) Reset()                    { *m = ChaincodeDeploymentSpec{} }
func (m *ChaincodeDeploymentSpec) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeDeploymentSpec) ProtoMessage()               {}
func (*ChaincodeDeploymentSpec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *ChaincodeDeploymentSpec) GetChaincodeSpec() *ChaincodeSpec {
	if m != nil {
		return m.ChaincodeSpec
	}
	return nil
}

func (m *ChaincodeDeploymentSpec) GetEffectiveDate() *google_protobuf1.Timestamp {
	if m != nil {
		return m.EffectiveDate
	}
	return nil
}

// Carries the chaincode function and its arguments.
type ChaincodeInvocationSpec struct {
	ChaincodeSpec *ChaincodeSpec `protobuf:"bytes,1,opt,name=chaincodeSpec" json:"chaincodeSpec,omitempty"`
	// This field can contain a user-specified ID generation algorithm
	// If supplied, this will be used to generate a ID
	// If not supplied (left empty), sha256base64 will be used
	// The algorithm consists of two parts:
	//  1, a hash function
	//  2, a decoding used to decode user (string) input to bytes
	// Currently, SHA256 with BASE64 is supported (e.g. idGenerationAlg='sha256base64')
	IdGenerationAlg string `protobuf:"bytes,2,opt,name=idGenerationAlg" json:"idGenerationAlg,omitempty"`
}

func (m *ChaincodeInvocationSpec) Reset()                    { *m = ChaincodeInvocationSpec{} }
func (m *ChaincodeInvocationSpec) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeInvocationSpec) ProtoMessage()               {}
func (*ChaincodeInvocationSpec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *ChaincodeInvocationSpec) GetChaincodeSpec() *ChaincodeSpec {
	if m != nil {
		return m.ChaincodeSpec
	}
	return nil
}

// ChaincodeProposalContext contains proposal data that we send to the chaincode
// container shim and allow the chaincode to access through the shim interface.
type ChaincodeProposalContext struct {
	// Creator corresponds to SignatureHeader.Creator
	Creator []byte `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	// Transient corresponds to ChaincodeProposalPayload.Transient
	// TODO: The transient field is supposed to carry application-specific
	// data. They might be realted to access-control, encryption and so on.
	// To simply access to this data, replacing bytes with a map
	// is the next step to be carried.
	Transient []byte `protobuf:"bytes,2,opt,name=transient,proto3" json:"transient,omitempty"`
}

func (m *ChaincodeProposalContext) Reset()                    { *m = ChaincodeProposalContext{} }
func (m *ChaincodeProposalContext) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeProposalContext) ProtoMessage()               {}
func (*ChaincodeProposalContext) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

type ChaincodeMessage struct {
	Type            ChaincodeMessage_Type       `protobuf:"varint,1,opt,name=type,enum=protos.ChaincodeMessage_Type" json:"type,omitempty"`
	Timestamp       *google_protobuf1.Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Payload         []byte                      `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Txid            string                      `protobuf:"bytes,4,opt,name=txid" json:"txid,omitempty"`
	ProposalContext *ChaincodeProposalContext   `protobuf:"bytes,5,opt,name=proposalContext" json:"proposalContext,omitempty"`
	// event emmited by chaincode. Used only with Init or Invoke.
	// This event is then stored (currently)
	// with Block.NonHashData.TransactionResult
	ChaincodeEvent *ChaincodeEvent `protobuf:"bytes,6,opt,name=chaincodeEvent" json:"chaincodeEvent,omitempty"`
}

func (m *ChaincodeMessage) Reset()                    { *m = ChaincodeMessage{} }
func (m *ChaincodeMessage) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeMessage) ProtoMessage()               {}
func (*ChaincodeMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *ChaincodeMessage) GetTimestamp() *google_protobuf1.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ChaincodeMessage) GetProposalContext() *ChaincodeProposalContext {
	if m != nil {
		return m.ProposalContext
	}
	return nil
}

func (m *ChaincodeMessage) GetChaincodeEvent() *ChaincodeEvent {
	if m != nil {
		return m.ChaincodeEvent
	}
	return nil
}

type PutStateInfo struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *PutStateInfo) Reset()                    { *m = PutStateInfo{} }
func (m *PutStateInfo) String() string            { return proto.CompactTextString(m) }
func (*PutStateInfo) ProtoMessage()               {}
func (*PutStateInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

type RangeQueryState struct {
	StartKey string `protobuf:"bytes,1,opt,name=startKey" json:"startKey,omitempty"`
	EndKey   string `protobuf:"bytes,2,opt,name=endKey" json:"endKey,omitempty"`
}

func (m *RangeQueryState) Reset()                    { *m = RangeQueryState{} }
func (m *RangeQueryState) String() string            { return proto.CompactTextString(m) }
func (*RangeQueryState) ProtoMessage()               {}
func (*RangeQueryState) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

type RangeQueryStateNext struct {
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
}

func (m *RangeQueryStateNext) Reset()                    { *m = RangeQueryStateNext{} }
func (m *RangeQueryStateNext) String() string            { return proto.CompactTextString(m) }
func (*RangeQueryStateNext) ProtoMessage()               {}
func (*RangeQueryStateNext) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

type RangeQueryStateClose struct {
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
}

func (m *RangeQueryStateClose) Reset()                    { *m = RangeQueryStateClose{} }
func (m *RangeQueryStateClose) String() string            { return proto.CompactTextString(m) }
func (*RangeQueryStateClose) ProtoMessage()               {}
func (*RangeQueryStateClose) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

type RangeQueryStateKeyValue struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *RangeQueryStateKeyValue) Reset()                    { *m = RangeQueryStateKeyValue{} }
func (m *RangeQueryStateKeyValue) String() string            { return proto.CompactTextString(m) }
func (*RangeQueryStateKeyValue) ProtoMessage()               {}
func (*RangeQueryStateKeyValue) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

type RangeQueryStateResponse struct {
	KeysAndValues []*RangeQueryStateKeyValue `protobuf:"bytes,1,rep,name=keysAndValues" json:"keysAndValues,omitempty"`
	HasMore       bool                       `protobuf:"varint,2,opt,name=hasMore" json:"hasMore,omitempty"`
	ID            string                     `protobuf:"bytes,3,opt,name=ID" json:"ID,omitempty"`
}

func (m *RangeQueryStateResponse) Reset()                    { *m = RangeQueryStateResponse{} }
func (m *RangeQueryStateResponse) String() string            { return proto.CompactTextString(m) }
func (*RangeQueryStateResponse) ProtoMessage()               {}
func (*RangeQueryStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *RangeQueryStateResponse) GetKeysAndValues() []*RangeQueryStateKeyValue {
	if m != nil {
		return m.KeysAndValues
	}
	return nil
}

func init() {
	proto.RegisterType((*ChaincodeID)(nil), "protos.ChaincodeID")
	proto.RegisterType((*ChaincodeInput)(nil), "protos.ChaincodeInput")
	proto.RegisterType((*ChaincodeSpec)(nil), "protos.ChaincodeSpec")
	proto.RegisterType((*ChaincodeDeploymentSpec)(nil), "protos.ChaincodeDeploymentSpec")
	proto.RegisterType((*ChaincodeInvocationSpec)(nil), "protos.ChaincodeInvocationSpec")
	proto.RegisterType((*ChaincodeProposalContext)(nil), "protos.ChaincodeProposalContext")
	proto.RegisterType((*ChaincodeMessage)(nil), "protos.ChaincodeMessage")
	proto.RegisterType((*PutStateInfo)(nil), "protos.PutStateInfo")
	proto.RegisterType((*RangeQueryState)(nil), "protos.RangeQueryState")
	proto.RegisterType((*RangeQueryStateNext)(nil), "protos.RangeQueryStateNext")
	proto.RegisterType((*RangeQueryStateClose)(nil), "protos.RangeQueryStateClose")
	proto.RegisterType((*RangeQueryStateKeyValue)(nil), "protos.RangeQueryStateKeyValue")
	proto.RegisterType((*RangeQueryStateResponse)(nil), "protos.RangeQueryStateResponse")
	proto.RegisterEnum("protos.ConfidentialityLevel", ConfidentialityLevel_name, ConfidentialityLevel_value)
	proto.RegisterEnum("protos.ChaincodeSpec_Type", ChaincodeSpec_Type_name, ChaincodeSpec_Type_value)
	proto.RegisterEnum("protos.ChaincodeDeploymentSpec_ExecutionEnvironment", ChaincodeDeploymentSpec_ExecutionEnvironment_name, ChaincodeDeploymentSpec_ExecutionEnvironment_value)
	proto.RegisterEnum("protos.ChaincodeMessage_Type", ChaincodeMessage_Type_name, ChaincodeMessage_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for ChaincodeSupport service

type ChaincodeSupportClient interface {
	Register(ctx context.Context, opts ...grpc.CallOption) (ChaincodeSupport_RegisterClient, error)
}

type chaincodeSupportClient struct {
	cc *grpc.ClientConn
}

func NewChaincodeSupportClient(cc *grpc.ClientConn) ChaincodeSupportClient {
	return &chaincodeSupportClient{cc}
}

func (c *chaincodeSupportClient) Register(ctx context.Context, opts ...grpc.CallOption) (ChaincodeSupport_RegisterClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ChaincodeSupport_serviceDesc.Streams[0], c.cc, "/protos.ChaincodeSupport/Register", opts...)
	if err != nil {
		return nil, err
	}
	x := &chaincodeSupportRegisterClient{stream}
	return x, nil
}

type ChaincodeSupport_RegisterClient interface {
	Send(*ChaincodeMessage) error
	Recv() (*ChaincodeMessage, error)
	grpc.ClientStream
}

type chaincodeSupportRegisterClient struct {
	grpc.ClientStream
}

func (x *chaincodeSupportRegisterClient) Send(m *ChaincodeMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chaincodeSupportRegisterClient) Recv() (*ChaincodeMessage, error) {
	m := new(ChaincodeMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ChaincodeSupport service

type ChaincodeSupportServer interface {
	Register(ChaincodeSupport_RegisterServer) error
}

func RegisterChaincodeSupportServer(s *grpc.Server, srv ChaincodeSupportServer) {
	s.RegisterService(&_ChaincodeSupport_serviceDesc, srv)
}

func _ChaincodeSupport_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChaincodeSupportServer).Register(&chaincodeSupportRegisterServer{stream})
}

type ChaincodeSupport_RegisterServer interface {
	Send(*ChaincodeMessage) error
	Recv() (*ChaincodeMessage, error)
	grpc.ServerStream
}

type chaincodeSupportRegisterServer struct {
	grpc.ServerStream
}

func (x *chaincodeSupportRegisterServer) Send(m *ChaincodeMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chaincodeSupportRegisterServer) Recv() (*ChaincodeMessage, error) {
	m := new(ChaincodeMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ChaincodeSupport_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ChaincodeSupport",
	HandlerType: (*ChaincodeSupportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _ChaincodeSupport_Register_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptor1,
}

func init() { proto.RegisterFile("peer/chaincode.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x56, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x0e, 0x25, 0xf9, 0xa0, 0x91, 0x2c, 0x6f, 0x36, 0x8a, 0xa3, 0x5f, 0x7f, 0xda, 0x08, 0x44,
	0x5b, 0xa8, 0xbd, 0x90, 0x53, 0x35, 0x29, 0x0a, 0x14, 0x08, 0xca, 0x90, 0x1b, 0x97, 0xb1, 0x4c,
	0x29, 0x2b, 0xda, 0x48, 0x7a, 0x63, 0xac, 0xa9, 0xb5, 0x4c, 0x44, 0xe6, 0x12, 0xe4, 0x4a, 0xb0,
	0xee, 0x7a, 0xdd, 0xab, 0xbe, 0x43, 0xdf, 0xa2, 0x2f, 0xd3, 0x57, 0x29, 0x96, 0x07, 0x59, 0xa7,
	0x00, 0x01, 0x7a, 0xc5, 0x9d, 0x99, 0xef, 0x1b, 0xce, 0x61, 0x67, 0x48, 0xa8, 0x87, 0x9c, 0x47,
	0xc7, 0xde, 0x0d, 0xf3, 0x03, 0x4f, 0x8c, 0x78, 0x27, 0x8c, 0x84, 0x14, 0x78, 0x37, 0x79, 0xc4,
	0xcd, 0xff, 0xad, 0x5a, 0xf9, 0x8c, 0x07, 0x32, 0x85, 0x34, 0x9f, 0x8d, 0x85, 0x18, 0x4f, 0xf8,
	0x71, 0x22, 0x5d, 0x4d, 0xaf, 0x8f, 0xa5, 0x7f, 0xcb, 0x63, 0xc9, 0x6e, 0xc3, 0x14, 0xa0, 0xbf,
	0x84, 0x8a, 0x99, 0x13, 0x6d, 0x0b, 0x63, 0x28, 0x85, 0x4c, 0xde, 0x34, 0xb4, 0x96, 0xd6, 0x2e,
	0xd3, 0xe4, 0xac, 0x74, 0x01, 0xbb, 0xe5, 0x8d, 0x42, 0xaa, 0x53, 0x67, 0xfd, 0x2b, 0xa8, 0xdd,
	0xd3, 0x82, 0x70, 0x2a, 0x15, 0x8a, 0x45, 0xe3, 0xb8, 0xa1, 0xb5, 0x8a, 0xed, 0x2a, 0x4d, 0xce,
	0xfa, 0x9f, 0x45, 0x38, 0x58, 0xc0, 0x86, 0x21, 0xf7, 0x70, 0x07, 0x4a, 0x72, 0x1e, 0xf2, 0xc4,
	0x7f, 0xad, 0xdb, 0x4c, 0x83, 0x88, 0x3b, 0x2b, 0xa0, 0x8e, 0x3b, 0x0f, 0x39, 0x4d, 0x70, 0xf8,
	0x25, 0x54, 0xbc, 0xfb, 0xf0, 0x92, 0x10, 0x2a, 0xdd, 0x47, 0x1b, 0x34, 0xdb, 0xa2, 0xcb, 0x38,
	0xfc, 0x1c, 0xf6, 0x3c, 0x29, 0xa2, 0xb3, 0x78, 0xdc, 0x28, 0x26, 0x94, 0xa3, 0x4d, 0x8a, 0x8a,
	0x9a, 0xe6, 0x30, 0xdc, 0x80, 0x3d, 0x55, 0x1a, 0x31, 0x95, 0x8d, 0x52, 0x4b, 0x6b, 0xef, 0xd0,
	0x5c, 0xc4, 0x03, 0xa8, 0x7b, 0x22, 0xb8, 0xf6, 0x47, 0x3c, 0x90, 0x3e, 0x9b, 0xf8, 0x72, 0xde,
	0xe3, 0x33, 0x3e, 0x69, 0xec, 0x24, 0x29, 0x3c, 0x5d, 0x38, 0xde, 0x82, 0xa1, 0x5b, 0x99, 0xb8,
	0x09, 0xfb, 0xb7, 0x5c, 0xb2, 0x11, 0x93, 0xac, 0xb1, 0xdb, 0xd2, 0xda, 0x55, 0xba, 0x90, 0xf1,
	0x97, 0x00, 0x4c, 0xca, 0xc8, 0xbf, 0x9a, 0x4a, 0x1e, 0x37, 0xf6, 0x5a, 0xc5, 0x76, 0x99, 0x2e,
	0x69, 0xf4, 0x57, 0x50, 0x52, 0xe5, 0xc1, 0x07, 0x50, 0x3e, 0x77, 0x2c, 0xf2, 0xc6, 0x76, 0x88,
	0x85, 0x1e, 0x60, 0x80, 0xdd, 0x93, 0x7e, 0xcf, 0x70, 0x4e, 0x90, 0x86, 0xf7, 0xa1, 0xe4, 0xf4,
	0x2d, 0x82, 0x0a, 0x78, 0x0f, 0x8a, 0xa6, 0x41, 0x51, 0x51, 0xa9, 0xde, 0x1a, 0x17, 0x06, 0x2a,
	0xe9, 0x7f, 0x17, 0xe0, 0xc9, 0xa2, 0x06, 0x16, 0x0f, 0x27, 0x62, 0x7e, 0xcb, 0x03, 0x99, 0x34,
	0xe7, 0x67, 0x38, 0xf0, 0x96, 0x1b, 0x91, 0x74, 0xa9, 0xd2, 0x7d, 0xbc, 0xb5, 0x4b, 0x74, 0x15,
	0x8b, 0x7f, 0x81, 0x03, 0x7e, 0x7d, 0xcd, 0x3d, 0xe9, 0xcf, 0xb8, 0xc5, 0x24, 0xcf, 0x7a, 0xd5,
	0xec, 0xa4, 0x37, 0xb0, 0x93, 0xdf, 0xc0, 0x8e, 0x9b, 0xdf, 0x40, 0xba, 0x4a, 0xc0, 0x2d, 0xa8,
	0x28, 0x6f, 0x03, 0xe6, 0x7d, 0x64, 0x63, 0x9e, 0x34, 0xae, 0x4a, 0x97, 0x55, 0xd8, 0x81, 0x3d,
	0x7e, 0xc7, 0x3d, 0x12, 0xcc, 0x92, 0x26, 0xd5, 0xba, 0x2f, 0x36, 0x42, 0x5b, 0x4d, 0xa9, 0x43,
	0xee, 0xb8, 0x37, 0x95, 0xbe, 0x08, 0x48, 0x30, 0xf3, 0x23, 0x11, 0x28, 0x03, 0xcd, 0x9d, 0xe8,
	0x1d, 0xa8, 0x6f, 0x03, 0xa8, 0x6a, 0x5a, 0x7d, 0xf3, 0x94, 0xd0, 0xb4, 0xb2, 0xc3, 0x0f, 0x43,
	0x97, 0x9c, 0x21, 0x4d, 0xff, 0x5d, 0x5b, 0x2a, 0x9e, 0x1d, 0xcc, 0x84, 0xc7, 0x14, 0xf5, 0xbf,
	0x17, 0xaf, 0x0d, 0x87, 0xfe, 0xe8, 0x84, 0x07, 0x3c, 0x4a, 0x1c, 0x1a, 0x93, 0x71, 0x36, 0x6d,
	0xeb, 0x6a, 0x9d, 0x42, 0x63, 0xe1, 0x69, 0x10, 0x89, 0x50, 0xc4, 0x6c, 0x62, 0x8a, 0x40, 0xf2,
	0x3b, 0xa9, 0xee, 0xb0, 0x17, 0x71, 0x26, 0x45, 0x94, 0xbc, 0xbc, 0x4a, 0x73, 0x11, 0x3f, 0x85,
	0xb2, 0x8c, 0x58, 0x10, 0xfb, 0x3c, 0x90, 0x89, 0xe7, 0x2a, 0xbd, 0x57, 0xe8, 0xff, 0x94, 0x00,
	0x2d, 0x9c, 0x9e, 0xf1, 0x38, 0x56, 0xb5, 0xfe, 0x7e, 0x65, 0x52, 0xbf, 0xd8, 0x48, 0x23, 0xc3,
	0x2d, 0x0f, 0xeb, 0x4f, 0x50, 0x5e, 0xac, 0x97, 0xcf, 0x68, 0xff, 0x3d, 0x58, 0x45, 0x1e, 0xb2,
	0xf9, 0x44, 0xb0, 0x51, 0xd6, 0xf6, 0x5c, 0x54, 0x6b, 0x45, 0xde, 0xf9, 0xa3, 0xa4, 0xdf, 0x65,
	0x9a, 0x9c, 0xf1, 0x5b, 0x38, 0x0c, 0x57, 0x53, 0x4f, 0x86, 0xb1, 0xd2, 0x6d, 0x6d, 0x44, 0xb9,
	0x56, 0x22, 0xba, 0x4e, 0xc4, 0xaf, 0xa0, 0xb6, 0x68, 0x05, 0x51, 0x8b, 0x33, 0x99, 0xc8, 0x6d,
	0x0b, 0x23, 0xb1, 0xd2, 0x35, 0xb4, 0xfe, 0x57, 0x61, 0xfb, 0x40, 0x56, 0x61, 0x9f, 0x92, 0x13,
	0x7b, 0xe8, 0x12, 0x8a, 0x34, 0x5c, 0x03, 0xc8, 0x25, 0x62, 0xa1, 0x82, 0x9a, 0x47, 0xdb, 0xb1,
	0x5d, 0x54, 0xc4, 0x65, 0xd8, 0xa1, 0xc4, 0xb0, 0x3e, 0xa0, 0x12, 0x3e, 0x84, 0x8a, 0x4b, 0x0d,
	0x67, 0x68, 0x98, 0xae, 0xdd, 0x77, 0xd0, 0x8e, 0x72, 0x69, 0xf6, 0xcf, 0x06, 0x3d, 0xe2, 0x12,
	0x0b, 0xed, 0x2a, 0x28, 0xa1, 0xb4, 0x4f, 0xd1, 0x9e, 0xb2, 0x9c, 0x10, 0xf7, 0x72, 0xe8, 0x1a,
	0x2e, 0x41, 0xfb, 0x4a, 0x1c, 0x9c, 0xe7, 0x62, 0x59, 0x89, 0x16, 0xe9, 0x65, 0x22, 0xe0, 0x3a,
	0x20, 0xdb, 0xb9, 0xe8, 0x9f, 0x92, 0x4b, 0xf3, 0x57, 0xc3, 0x76, 0x4c, 0xb5, 0x1b, 0x2a, 0x69,
	0x80, 0xc3, 0x41, 0xdf, 0x19, 0x12, 0x74, 0x80, 0x1f, 0xc3, 0x43, 0x6a, 0x38, 0x27, 0xe4, 0xf2,
	0xdd, 0x39, 0xa1, 0x1f, 0x32, 0x6a, 0x0d, 0x37, 0xe1, 0x68, 0x43, 0x7d, 0xe9, 0x90, 0xf7, 0x2e,
	0x3a, 0xc4, 0xff, 0x87, 0x27, 0x9b, 0x36, 0xb3, 0xd7, 0x1f, 0x12, 0x84, 0x54, 0x08, 0xa7, 0x84,
	0x0c, 0x8c, 0x9e, 0x7d, 0x41, 0xd0, 0x43, 0xfd, 0x47, 0xa8, 0x0e, 0xa6, 0x72, 0x28, 0x99, 0xe4,
	0x76, 0x70, 0x2d, 0x30, 0x82, 0xe2, 0x47, 0x3e, 0xcf, 0xbe, 0x32, 0xea, 0x88, 0xeb, 0xb0, 0x33,
	0x63, 0x93, 0x29, 0xcf, 0x6e, 0x67, 0x2a, 0xe8, 0x04, 0x0e, 0x29, 0x0b, 0xc6, 0xfc, 0xdd, 0x94,
	0x47, 0xf3, 0x84, 0xae, 0x96, 0x67, 0x2c, 0x59, 0x24, 0x4f, 0x17, 0xfc, 0x85, 0x8c, 0x8f, 0x60,
	0x97, 0x07, 0x23, 0x65, 0x49, 0xa7, 0x27, 0x93, 0xf4, 0xaf, 0xe1, 0xd1, 0x9a, 0x1b, 0x47, 0xf5,
	0xbe, 0x06, 0x05, 0xdb, 0xca, 0x9c, 0x14, 0x6c, 0x4b, 0xff, 0x06, 0xea, 0x6b, 0x30, 0x73, 0x22,
	0x62, 0xbe, 0x81, 0x33, 0xe0, 0xc9, 0x1a, 0xee, 0x94, 0xcf, 0x2f, 0x54, 0xc0, 0x9f, 0x9d, 0xd8,
	0x1f, 0xda, 0x86, 0x0f, 0xca, 0xe3, 0x50, 0x04, 0x31, 0xc7, 0x04, 0x0e, 0x3e, 0xf2, 0x79, 0x6c,
	0x04, 0xa3, 0xc4, 0x67, 0xfa, 0x49, 0xad, 0x74, 0x9f, 0xe5, 0x37, 0xf2, 0x13, 0xef, 0xa6, 0xab,
	0x2c, 0x35, 0x53, 0x37, 0x2c, 0x3e, 0x13, 0x51, 0xfa, 0xea, 0x7d, 0x9a, 0x8b, 0x59, 0x3e, 0xc5,
	0x3c, 0x9f, 0xef, 0x5e, 0x40, 0x7d, 0xdb, 0xd7, 0x4b, 0xad, 0xbe, 0xc1, 0xf9, 0xeb, 0x9e, 0x6d,
	0xa2, 0x07, 0x18, 0x41, 0xd5, 0xec, 0x3b, 0x6f, 0x6c, 0x8b, 0x38, 0xae, 0x6d, 0xf4, 0x90, 0xd6,
	0x7d, 0xbf, 0xb4, 0x34, 0x86, 0xd3, 0x30, 0x14, 0x91, 0xc4, 0x16, 0xec, 0x53, 0x3e, 0xf6, 0x63,
	0xc9, 0x23, 0xdc, 0xf8, 0xd4, 0xca, 0x68, 0x7e, 0xd2, 0xa2, 0x3f, 0x68, 0x6b, 0xcf, 0xb5, 0xd7,
	0x26, 0x1c, 0x89, 0x68, 0xdc, 0xb9, 0x99, 0x87, 0x3c, 0x9a, 0xf0, 0xd1, 0x98, 0x47, 0x19, 0xe1,
	0xb7, 0x6f, 0xc7, 0xbe, 0xbc, 0x99, 0x5e, 0x75, 0x3c, 0x71, 0x7b, 0xbc, 0x64, 0x3e, 0xbe, 0x66,
	0x57, 0x91, 0xef, 0xa5, 0x7f, 0x39, 0xf1, 0xb1, 0xfa, 0x1d, 0xba, 0x4a, 0x7f, 0x8e, 0x7e, 0xf8,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x94, 0xee, 0x4d, 0x7b, 0x3b, 0x09, 0x00, 0x00,
}
