FROM hyperledger/fabric-baseimage:_BASE_TAG_

# fabric configuration locations
ENV PEER_CFG_PATH /etc/hyperledger/fabric
ENV ORDERER_CFG_PATH /etc/hyperledger/fabric/orderer

# create needed directories
RUN mkdir -p \
  $PEER_CFG_PATH \
  $ORDERER_CFG_PATH \
  /var/hyperledger/production

# install gotools
ADD payload/gotools.tar.bz2 /usr/local/bin/

# fabric configuration files
COPY payload/orderer.yaml $ORDERER_CFG_PATH
COPY payload/core.yaml $PEER_CFG_PATH
ADD payload/msp-sampleconfig.tar.bz2 $PEER_CFG_PATH


# fabric binaries
COPY payload/orderer /usr/local/bin
COPY payload/peer /usr/local/bin

# softhsm2
COPY payload/install-softhsm2.sh /tmp
RUN bash /tmp/install-softhsm2.sh && rm -f install-softhsm2.sh

# typically, this is mapped to a developer's dev environment
WORKDIR /opt/gopath/src/github.com/hyperledger/fabric
